Remove static pipeline
rust-vmm/rust-vmm-ci pull request #85
Opened 2021-09-06 10:21 UTC by catalindumitru

The use of the static file `pipeline.yml` is now deprecated. All pipelines should use the dynamic script `autogenerate_pipeline.py`.

2021-09-06 10:41 UTC, andreeaflorescu requested changes
Let's wait to first merge the dependabot update so we don't get spammed with PRs daily again.

2021-09-15 06:56 UTC, lauralt approved these changes
I just noticed that [this section](https://github.com/rust-vmm/rust-vmm-ci/blob/main/README.md#custom-pipeline) is a bit outdated, but we can update it in a separate PR.

2021-09-16 09:00 UTC, lauralt approved these changes

2021-09-16 13:31 UTC, andreeaflorescu approved these changes

2021-09-16 13:34 UTC, merged